### ISSUE TITLE
Error unmarshal string

### ISSUE THREAD

**Issue by ericllistar** [zarplata/zabbix-agent-extension-rabbitmq#11]
I'm having problems discovering queues and some other data.
When I send the command in order to debug then not supported message, I received:

[t|json: cannot unmarshal string into Go struct field QueueInfo.consumer_utilisation of type float64]

Please anyone can help me?

Thanks

**Comment by tears-of-noobs** [comment]
Hey @ericllistar. Could you please provide a little bit more information. What version of the extension do you use? What version of RabbitMQ? What command leads to the error message?

**Comment by ericllistar** [comment]
Sure! Sorry days ago this description had sense in my mind, but now.... reading again.... I don't understand anything hahaha.

I've installed that extension for Zabbix agent, and import the template.
And then the item "Template App Rabbitmq Service: RabbitMQ stats" give me that output: 
Cannot evaluate expression: "Cannot evaluate function "10.13.0.86:rabbitmq.stats[{$ZABBIX_SERVER_IP},{$RABBITMQ_MGMT_ADDRESS},{$RABBITMQ_USER},{$RABBITMQ_PASSWORD},{$RABBITMQ_CA_PATH},{HOST.HOST}].regexp(OK)": item is not supported.".

So, in order to debug that error I check it directly on target machine (rabbitmq machine):
COMMAND --> zabbix_agentd -t rabbitmq.stats[10.13.3.23,http://127.0.0.1:15672,user,password,/,10.13.0.86]
And that's giving me the following error:
ERROR --> [t|json: cannot unmarshal string into Go struct field QueueInfo.consumer_utilisation of type float64]

I'm very newbie in go and don't know how to solve that

I'm using Zabbix Server 4.2, Zabbix Agent 4.2 also. The rabbit version is 3.3.0

Thanks for your patience

**Comment by tears-of-noobs** [comment]
Hmm, it seems to the RabbitMQ has a too old version (5 y) and management API doesn't support several fields.
This exception happens when extension trying to unmarshalling `JSON` data into `Go` struct [QueueInfo](https://github.com/michaelklishin/rabbit-hole/blob/master/queues.go#L67)
Could you please ask API directly via curl and try to find `consumer_utilisation` field?

URL for checking - `curl -u user:password -H "content-type:application/json" http://RABBITMQ_ADDR:15672/api/queues` 
For lastest version of RabbitMQ (3.6, 3.7) these field looks like 
```json
    "memory": 198460,
    "consumer_utilisation": 0.8916439525099574,
    "consumers": 1,
    "exclusive_consumer_tag": null,
    "effective_policy_definition": {
      "ha-mode": "all",
      "dead-letter-routing-key": "api.events.dead",
      "dead-letter-exchange": "events-firehose"
    },
    "operator_policy": null,
    "policy": "dlx-api.events"
  },

```
