### ISSUE TITLE
Not receiving some data

### ISSUE THREAD

**Issue by cmmata** [zarplata/zabbix-agent-extension-rabbitmq#5]
Hello,

I have an issue like #1, but I don't see how it was resolved. I have zabbix extension running but not receiving some data. I have checked hostname, zabbix-agent and zabbix-server name and they are all the same.

![screenshot](https://user-images.githubusercontent.com/4223148/54024267-978d5580-4197-11e9-8af6-5b84a28d5ecf.png)

Also, I have an error in discovery. I don't know if that's the problem
![screenshot2](https://user-images.githubusercontent.com/4223148/54024398-fe127380-4197-11e9-9d1a-2459bea4e1e0.png)

_Originally posted by @cmmata in https://github.com/zarplata/zabbix-agent-extension-rabbitmq/issues/1#issuecomment-470886879_

**Comment by tears-of-noobs** [comment]
@cmmata Well, as I see you don't receive data about `RabbitMQ port listen` and  `RabbitMQ process num`. Both of them it's a part of built-in zabbix-agent functionality called - `Simple checks` https://www.zabbix.com/documentation/3.4/manual/config/items/itemtypes/simple_checks and for correct work you need to have installed zabbix-agent on the same node where RabbitMQ running. But if you have non-default configuration it may lead to several problems.

At first about `RabbitMQ port listen`:
- If you use a non-standard port - you should change the template macros `{$RABBITMQ_PORT}`
- Item, by default collect with key - `net.tcp.service[tcp,,{$RABBITMQ_PORT}]` and it means that `zabbix-agent` checks TCP port on "default interface", "default interface" in this context - IP or hostname which you describe in `zabbix-agent` config. So if you bind your RabbitMQ server on a custom network interface  - this check may be failed. Please, provide a little bit more information about your configuration to help me resolve this issue.

About `RabbitMQ process num`

- There were a bug and I fix it by this commit - https://github.com/zarplata/zabbix-agent-extension-rabbitmq/commit/3d15086e7157ae590dc5ce26db4c739b0c09c30a

About discovery:
I think it's not an error because it does not affect ether on discovered items or static items.

**Comment by cmmata** [comment]
Thanks @tears-of-noobs, I fixed the `process num` error with that bugfix. I understood how `port listen` were running thanks to your explanation, and checked the internal linux firewall. Port 5672 was not listed, so I added it. I don't know if it's because of the firewall (zabbix-agent and rabbitmq are in the same server) or because of the updated repo, but now both values return a `1`.

Now the only problem is discovery, that throws a `Value should be a JSON object.` instead of the problem in the screenshot. I see there's a `$GROUPNAME` variable, can it be because of that? I don't have a macro for that.

**Comment by tears-of-noobs** [comment]
Yes, I’ve already fixed this problem by the last commit. Reinstall extension, agent configuration and reimport template.

**Comment by tears-of-noobs** [comment]
@cmmata Let me know, did you solve your problem with discovery?

**Comment by cmmata** [comment]
Okay, now it's working! I'm receiving static and discovered data from rabbitmq. Thank you!

By the way, I think the discovery rules are trying to create the same objects again, because when I reinstalled the template, there was no error in discovery, and now I'm seeing the same as in the screenshot

```
Cannot create item: item with the same key "grpavg["{#GROUPNAME}", "rabbitmq.queue.messages[{#AGGQUEUENAME}]",last,0]" already exists.
Cannot create item: item with the same key "grpavg["{#GROUPNAME}", "rabbitmq.queue.messages_stats.deliver[{#AGGQUEUENAME}]",last,0]" already exists.
Cannot create item: item with the same key "grpavg["{#GROUPNAME}", "rabbitmq.queue.messages_stats.redeliver[{#AGGQUEUENAME}]",last,0]" already exists.
Cannot create item: item with the same key "grpavg["{#GROUPNAME}", "rabbitmq.queue.messages_stats.publish[{#AGGQUEUENAME}]",last,0]" already exists.
Cannot create item: item with the same key "grpavg["{#GROUPNAME}", "rabbitmq.queue.messages[{#AGGQUEUENAME}]",last,0]" already exists.
Cannot create item: item with the same key "grpavg["{#GROUPNAME}", "rabbitmq.queue.messages_stats.deliver[{#AGGQUEUENAME}]",last,0]" already exists.
Cannot create item: item with the same key "grpavg["{#GROUPNAME}", "rabbitmq.queue.messages_stats.publish[{#AGGQUEUENAME}]",last,0]" already exists.
Cannot create item: item with the same key "grpavg["{#GROUPNAME}", "rabbitmq.queue.messages_stats.redeliver[{#AGGQUEUENAME}]",last,0]" already exists.
```

**Comment by tears-of-noobs** [comment]
@cmmata I found the bug which results in a discovery error in a web interface and I fixed it by this commit - https://github.com/zarplata/zabbix-agent-extension-rabbitmq/commit/540d85ed8d90c6cfb220f3e149bd1e05d13df9bd. 
You should reinstall the extension, again :grin:

**Comment by cmmata** [comment]
@tears-of-noobs looks great! I reinstalled all, and now there isn't any error in discovery, and zabbix is monitoring all data. Looks like the plugin finished the testing phase. :rofl: Thank you!
